# Logging levels
logging:
  level:
    org.springframework: ERROR
    org.springframework.security: INFO
    org.hibernate: ERROR

# Hystrix timeout time (60 secs)
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

# Enable hystrix for feign clients
feign:
  hystrix.enabled: true
  client.config.default.loggerLevel: full

# Enable actuator endpoints
management.endpoints.web.exposure.include: '*'

# USING MYSQL
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: ${DB_DDL_AUTO}

# Eureka client configs
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${MMN_CORE_REGISTRY_HOST:localhost}:${MMN_CORE_REGISTRY_PORT:8082}/${MMN_CORE_REGISTRY_CONTEXTPATH:eureka}/

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://${MMN_BUSINESS_AUTH_HOST:localhost}:${MMN_BUSINESS_AUTH_PORT:8180}/${MMN_BUSINESS_AUTH_CONTEXTPATH:uaa}/users/current
