# RANDOM PORT
server.port: 0

info.app:
  name: Travined - Mail Service
  description: Spring boot application
  version: 1.0.0

#security:
#  oauth2:
#    client:
#      clientId: ${MMN_BUSINESS_AUTH_NAME:business-auth-service}
#      clientSecret: ${MMN_BUSINESS_AUTH_PASSWORD:Password1234}
#
#      accessTokenUri: http://${MMN_BUSINESS_AUTH_HOST:localhost}:${MMN_BUSINESS_AUTH_PORT:8180}/${MMN_BUSINESS_AUTH_CONTEXTPATH:uaa}/oauth/token
#
#      grant-type: client_credentials
#      scope: server
