server:
  port: ${MMN_CORE_GATEWAY_PORT:8080}

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  prefix: /api
  routes:
    #${MMN_BUSINESS_AUTH_NAME:business-auth-service}:
    #  #path: /${MMN_BUSINESS_AUTH_CONTEXTPATH:uaa}/**
    #  path: /**
    #  serviceId: ${MMN_BUSINESS_AUTH_NAME:business-auth-service}
    #  stripPrefix: false

    ${MMN_BUSINESS_ACCOUNT_NAME:business-account-service}:
      path: /${MMN_BUSINESS_ACCOUNT_CONTEXTPATH:accounts}/**
      #path: /**
      serviceId: ${MMN_BUSINESS_ACCOUNT_NAME:business-account-service}

    ${MMN_BUSINESS_PAYMENT_NAME:business-payment-service}:
      path: /${MMN_BUSINESS_PAYMENT_CONTEXTPATH:payments}/**
      #path: /**
      serviceId: ${MMN_BUSINESS_PAYMENT_NAME:business-payment-service}

    ${MMN_BUSINESS_TRANSLATION_NAME:business-translation-service}:
      path: /${MMN_BUSINESS_TRANSLATION_CONTEXTPATH:translations}/**
      #path: /**
      serviceId: ${MMN_BUSINESS_TRANSLATION_NAME:business-translation-service}

    ${MMN_BUSINESS_MAIL_NAME:business-mail-service}:
      path: /${MMN_BUSINESS_MAIL_CONTEXTPATH:mail}/**
      #path: /**
      serviceId: ${MMN_BUSINESS_MAIL_NAME:business-mail-service}

